# {{REPO_NAME}}

![status](https://img.shields.io/badge/generated--by-radar__love.sh-brightgreen)
![demo](https://img.shields.io/badge/demo-vault--radar--ready-blue)
![Oasis](https://img.shields.io/badge/inspired--by-Oasis-yellow)

> “I think you’re the same as me, we see things they’ll never see...” — *Oasis*

---

## 🎯 Purpose

**A flexible, CLI-driven toolkit to simulate real-world code leaks—secrets, PII, and non-inclusive language—designed to test Vault Radar, Gitleaks, TruffleHog, and other scanners.**

---

## ⚙️ How It Works

1. **Edit your `Vault_Radar_input.json`:**
   - Add/remove leaks, tweak values, assign languages, set scenario/severity.

2. **Run the builder:**
   ```bash
   chmod +x ../vault_radar_builder.sh
   ../vault_radar_builder.sh --output-path . --languages bash,python --scenario AWS --lint

Flags:

--languages: Select scripts to generate (bash, python, node, terraform, dockerfile)
--scenario: Filter leaks (e.g., AWS, PII)
--header-template / --footer-template: Inject custom banners
--lint: Run sanity checks
--dry-run: Preview mode
--quiet: Silent mode

📦 Output Files

Vault_Radar_trigger.sh (Bash)
Vault_Radar_trigger.py (Python)
Vault_Radar_trigger.js (Node.js)
Vault_Radar_trigger.Dockerfile (Docker)
Vault_Radar_trigger.tf (Terraform)
Vault_Radar_leaks_report.md (Markdown report)
Vault_Radar_cleanup.sh (Removes everything)
Vault_Radar_build.log (Log file)
sanity_check_report.md (Optional, if --lint used)

🚦 Example Usage:

- All leaks (default):
    ../vault_radar_builder.sh --output-path . --scenario AWS

- Bash + Python, with lint:
    ../vault_radar_builder.sh --output-path . --languages bash,python --lint

- Dry-run Node + Terraform:
    - ../vault_radar_builder.sh --output-path . --languages node,terraform --dry-run

🔧 Customization

🧠 Vault_Radar_input.json — Edit/add leaks
🖼️ templates/ — Custom header/footer banners
🎯 Scenario filters — Focus on AWS, PII, etc.
🎲 Random output size — Optional realism
📝 Notes

“In my mind my dreams are real...” — Oasis

These scripts are for demo/educational use only.

Never commit real secrets or PII.

Works with: HashiCorp Vault Radar (https://www.hashicorp.com/en/products/vault/hcp-vault-radar)

📅 Auto-generated by radar_love.sh on {{DATE}}

© 2025 Raymon Epping — Open-source demo framework for secret scanning