name: Bump Bash Script Versions

on:
  push:
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bash and tools
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          chmod +x ./bump_version.sh
          chmod +x ./*.sh

      - name: Bump patch version for changed .sh scripts
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.sh$' || true)
          for file in $CHANGED_FILES; do
            ./bump_version.sh "$file" --patch || true
          done

      - name: Commit and push version bumps
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          # Robust cross-platform recursive git add (no globs)
          find . -type f -name '*.sh' -exec git add {} +
          find . -type f -name 'CHANGELOG_*.md' -exec git add {} +
          git diff --cached --quiet || git commit -m "ci: auto-bump Bash script versions [ci skip]"
          git push
