name: Generate Bash Documentation

on:
  push:
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bash and permissions
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          chmod +x ./generate_documentation.sh

      - name: Generate docs for all scripts
        run: |
          mkdir -p documentation
          ./generate_documentation.sh *.sh
          # Or, for all scripts in repo:
          # find . -name '*.sh' -exec ./generate_documentation.sh {} +

      - name: Upload generated docs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bash-docs
          path: documentation

      # Optional: Commit docs back to the repository (requires GITHUB_TOKEN and write permissions)
      - name: Commit and push updated docs
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add documentation/
          git diff --cached --quiet || git commit -m "Automated docs update [ci skip]"
          git push
