name: Generate Bash Documentation

on:
  push:
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up UTF-8 locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          export LANGUAGE=en_US.UTF-8

      - name: Set up Bash and permissions
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          chmod +x ./generate_documentation.sh
          chmod +x ./*.sh

      - name: Generate docs for all scripts
        run: |
          mkdir -p docs
          find . -name '*.sh' -exec ./generate_documentation.sh {} +

      - name: Upload generated docs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bash-docs
          path: docs

      - name: Commit and push updated docs
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add docs/
          git diff --cached --quiet || git commit -m "Automated docs update [ci skip]"
          git push
