name: Generate Bash Documentation

on:
  push:
    branches: [main]
    paths:
      - '**.sh'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up UTF-8 locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8
          export LANGUAGE=en_US.UTF-8

      - name: Set up Bash and permissions
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          chmod +x ./generate_documentation.sh
          chmod +x ./*.sh

      - name: Get changed .sh files
        id: changed
        run: |
          # List .sh files changed in this push compared to the previous commit
          git fetch origin ${{ github.event.before }}
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.sh$' || true
        shell: bash
        continue-on-error: true

      - name: Generate docs only for changed scripts
        run: |
          mkdir -p docs
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.sh$' || true)
          for file in $CHANGED_FILES; do
            # Remove ./ if present
            cleanfile="${file#./}"
            ./generate_documentation.sh "$cleanfile"
          done

      - name: Upload generated docs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bash-docs
          path: docs

      - name: Commit and push updated docs
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          # Only add changed docs (not full docs folder!)
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.sh$' || true)
          for file in $CHANGED_FILES; do
            docfile="docs/$(basename "${file%.sh}").md"
            if [[ -f "$docfile" ]]; then
              git add "$docfile"
            fi
          done
          git diff --cached --quiet || git commit -m "Automated docs update [ci skip]"
          git pull --rebase --autostash
          git push
